- name: Installing VSCode
  raw: flatpak install --from --assumeyes https://flathub.org/repo/appstream/com.visualstudio.code.flatpakref
  when: ansible_version.major >= 2 and ansible_version.minor < 6
