- name: Downloading Skype needed packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - alsa-lib
    - pulseaudio
    - glibc
    - libXv
    - libXScrnSaver

- name: Downloading Skype RPM
  get_url:
    url: https://go.skype.com/skypeforlinux-64.rpm
    dest: /tmp/skypeforlinux-64.rpm
    owner: frederico.ferreira
    group: frederico.ferreira

- name: Installing Skype
  dnf:
    name: /tmp/skypeforlinux-64.rpm
    state: present
