- name: Downloading Telegram
  get_url:
    url: https://telegram.org/dl/desktop/linux
    dest: /tmp/telegram.tar.xz

- name: Unpacking Telegram
  unarchive:
    src: /tmp/telegram.tar.xz
    dest: /opt
    owner: frederico.ferreira
    group: frederico.ferreira
