- name: get Anatine DEB
  get_url:
    url=https://github.com/sindresorhus/anatine/releases/download/1.1.0/Anatine-linux-1.1.0.zip
    dest=/tmp/Anatine-linux-1.1.0.zip
    mode=0755

- name: Creating Anatine dir
  file:
    path: /opt/Anatine
    state: directory

- name: install Anatine Twitter Client
  unarchive:
    src=/tmp/Anatine-linux-1.1.0.zip
    dest=/opt/Anatine
