- name: Install apt-transport-https
  apt:
    name=apt-transport-https
    update_cache=yes
    force=yes

- name: Add Skype key
  apt_key:
    url: "https://repo.skype.com/data/SKYPE-GPG-KEY"
    state: present

- name: Add Skype Repo
  apt_repository:
    repo: deb https://repo.skype.com/deb stable main
    state: present
    filename: /etc/apt/sources.list.d/skypeforlinux.list

- name: install Skype
  apt:
    name={{ item }}
    update_cache=yes
    force=yes
  with_items:
    - skypeforlinux
