- name: Add Tilix Repo
  apt_repository:
    repo: "ppa:webupd8team/terminix"
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: install Tilix
  apt:
    name={{ item }}
    update_cache=yes
  with_items:
    - tilix
