- name: Add Java Repo
  apt_repository:
    repo: "ppa:webupd8team/java"
    state: present

- name: No asking about it
  raw: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: install Java 8
  apt:
    name={{ item }}
    update_cache=yes
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
