- name: installing easy_install
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python-setuptools
    - python3-setuptools

- name: installing pip
  easy_install:
    name: pip
    executable: "{{ item }}"
  with_items:
    - easy_install
    - easy_install3
