- include_tasks: fedora/flatpak.yml
  tags:
    - flatpak
    - setup
- include_tasks: fedora/snap.yml
  tags:
    - snap
    - setup
- include_tasks: fedora/upgrade.yml
  tags:
    - upgrade
    - setup
