- include_tasks: ubuntu/flatpak.yml
  tags:
    - flatpak
    - setup
- include_tasks: ubuntu/snap.yml
  tags:
    - snap
    - setup
- include_tasks: ubuntu/upgrade.yml
  tags:
    - upgrade
    - setup
